version: "2"

services:
  mysql:
    image: mysql
    volumes:
      - mysql-volume:/var/lib/mysql
    restart: on-failure


  keystone:
    image: keystone
    build:
      context: keystone
    restart: on-failure


volumes:
  mysql-volume:
